-- AlterTable
ALTER TABLE `Email` ADD COLUMN `verified` ENUM('VERIFIED', 'UNVERIFIED') NOT NULL DEFAULT 'VERIFIED';

-- AlterTable
ALTER TABLE `User` ADD COLUMN `role` ENUM('OWNER', 'BASIC') NOT NULL DEFAULT 'BASIC';
